pool:
  vmImage: 'ubuntu-latest'

trigger:
 branches:
   include:
     - main
     - dev
     - hotfix*
     - feature*
 paths:
   exclude:
     - "*pipeline.yaml"
     - "*config.yaml"
     - "*.json"
resources:
  repositories: 
  - repository: azure-pipeline-template
    type: git
    ref: refs/heads/multi-countries
    name: Digital and Data Program Management/azure-pipeline-template
    endpoint: build-service

variables:
  - name: app-name
    value: 'corporate'
  - group: sitecore-CICD
  - name: date
    value: $[format('{0:yyyyMMdd}', pipeline.startTime)]
  - name: chartPath
    value: helm


stages:
- stage: Build_Push_Docker_Image
  displayName: Build and push docker image
  condition: or(eq(variables['Build.SourceBranchName'], 'dev'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'))
  jobs:
  - job: Version
    displayName: Generate Version number
    steps:
    - script:
        echo "$(Build.SourceVersion)"
      displayName: Setting pipeline run name


  - job: Docker
    displayName: Build and push docker image
    dependsOn: 'Version'
    steps:
    - template: steps/build_push_docker_image.yml@azure-pipeline-template
      parameters:
        tag: $(Build.SourceVersion)
        imageRepository: $(imageRepository)
        dockerRegistryServiceConnection: $(dockerRegistryServiceConnection)
        dockerfilePath: $(dockerfilePath)
